// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"github.com/google/uuid"
	"github.com/wenerme/ent-demo/ent/pet"
	"github.com/wenerme/ent-demo/ent/schema"
	"github.com/wenerme/ent-demo/ent/serviceaccount"
	"github.com/wenerme/ent-demo/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	petMixin := schema.Pet{}.Mixin()
	petMixinHooks0 := petMixin[0].Hooks()
	pet.Hooks[0] = petMixinHooks0[0]
	petMixinFields0 := petMixin[0].Fields()
	_ = petMixinFields0
	petFields := schema.Pet{}.Fields()
	_ = petFields
	// petDescUID is the schema descriptor for uid field.
	petDescUID := petMixinFields0[1].Descriptor()
	// pet.DefaultUID holds the default value on creation for the uid field.
	pet.DefaultUID = petDescUID.Default.(func() uuid.UUID)
	serviceaccountMixin := schema.ServiceAccount{}.Mixin()
	serviceaccountMixinFields0 := serviceaccountMixin[0].Fields()
	_ = serviceaccountMixinFields0
	serviceaccountFields := schema.ServiceAccount{}.Fields()
	_ = serviceaccountFields
	// serviceaccountDescDisplayName is the schema descriptor for displayName field.
	serviceaccountDescDisplayName := serviceaccountFields[0].Descriptor()
	// serviceaccount.DisplayNameValidator is a validator for the "displayName" field. It is called by the builders before save.
	serviceaccount.DisplayNameValidator = serviceaccountDescDisplayName.Validators[0].(func(string) error)
	// serviceaccountDescDisabled is the schema descriptor for disabled field.
	serviceaccountDescDisabled := serviceaccountFields[1].Descriptor()
	// serviceaccount.DefaultDisabled holds the default value on creation for the disabled field.
	serviceaccount.DefaultDisabled = serviceaccountDescDisabled.Default.(bool)
	// serviceaccountDescID is the schema descriptor for id field.
	serviceaccountDescID := serviceaccountMixinFields0[0].Descriptor()
	// serviceaccount.DefaultID holds the default value on creation for the id field.
	serviceaccount.DefaultID = serviceaccountDescID.Default.(func() string)
	userMixin := schema.User{}.Mixin()
	userMixinHooks0 := userMixin[0].Hooks()
	user.Hooks[0] = userMixinHooks0[0]
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUID is the schema descriptor for uid field.
	userDescUID := userMixinFields0[1].Descriptor()
	// user.DefaultUID holds the default value on creation for the uid field.
	user.DefaultUID = userDescUID.Default.(func() uuid.UUID)
}

const (
	Version = "v0.10.2-0.20220502113020-4ac82f5bb3f0" // Version of ent codegen.
)
