// Code generated by entc, DO NOT EDIT.

package ent

import "context"

func (pe *Pet) OwningUser(ctx context.Context) (*User, error) {
	result, err := pe.Edges.OwningUserOrErr()
	if IsNotLoaded(err) {
		result, err = pe.QueryOwningUser().Only(ctx)
	}
	return result, MaskNotFound(err)
}
