// Code generated by entc, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedByID holds the string denoting the createdbyid field in the database.
	FieldCreatedByID = "created_by_id"
	// EdgeCreatedBy holds the string denoting the createdby edge name in mutations.
	EdgeCreatedBy = "createdBy"
	// Table holds the table name of the user in the database.
	Table = "users"
	// CreatedByTable is the table the holds the createdBy relation/edge.
	CreatedByTable = "users"
	// CreatedByColumn is the table column denoting the createdBy relation/edge.
	CreatedByColumn = "created_by_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldCreatedByID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
